language: php

env:
  secure: "XXs0Yt6xDqGAJz07SfI2bDFiUVGfJvsS9ySaMO02sYvsEmkgW8vZcefuQBeM+Onevtbu8fcF3DmNhg/4DXS+hGT5XiZkRcDEC2OeBWY9pTZ+ZdknCHPYFfA9W1s+4K3VT1xIv1DnSmkMXr6WCDLws+Yrtq97+6n6RCZLQknaT3k="

cache:
  directories:
    - $HOME/.composer/cache/files

git:
  depth: 10

sudo: false

php:
  - 5.5
  - 5.6
  - 7
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update --no-interaction --no-progress --snapshot
  - composer config --no-interaction --global github-oauth.github.com $GITHUB_TRAVIS_TOKEN

install:
  - composer install --no-interaction --no-progress --prefer-dist --optimize-autoloader

script:
  - vendor/bin/phpunit
